video_root: '/mnt/main/zjcai/msrvtt/MSRVTT_Videos_Compression'
train_split_root: '/mnt/main/zjcai/msrvtt/MSRVTT_train.9k.csv'
test_split_root: '/mnt/main/zjcai/msrvtt/MSRVTT_JSFUSION_test.csv'
data_root: '/mnt/main/zjcai/msrvtt/MSRVTT_data.json'
dataset: 'retrieval_msrvtt'

# set pretrained as a file path or an url
pretrained: '/mnt/main/zjcai/BLIP-ToMe/pretrained/model_base.pth'

max_words: 32

# vit video encoder
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

batch_size_train: 4
batch_size_test: 16
init_lr: 1e-5

num_frames: 24
num_frm_train: 24
num_frm_test: 24

image_size: 224
queue_size: 57600
alpha: 0.4
k_test: 128
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 0

#ToMe 
token_merging: False
trace_source: False
tome_r: [120, 48, 48, 48, 48, 32, 32, 32, 32, 32, 32, 32]
tome_prop_attn: True
tome_type: 'soft_s_multi_cls'
tome_min_token: 1
tome_hierarchy: True
tome_token_importance: False
tome_importance_alpha: 6.0
frame_flatten_type: "keep"
tome_average_type: "AVG"
frame_flatten_layer: [0, 4, 8]
frame_mask: False
attn_frame_mask_layer: []
merge_frame_mask_layer: []
binary_frame_mask: False
flatten_layer_merge_type: ["T", "T", "S"]
enable_frame_pos_embed: False

#WeiMe
weights_merging: True
weime_r: 1000
weime_layers: [6]