video_root: '/mnt/main/zjcai/flicker30/flickr30k-images'
ann_root: '/mnt/main/zjcai/flicker30'
dataset: 'retrieval_flicker'

# set pretrained as a file path or an url
pretrained: '/mnt/main/zjcai/BLIP-ToMe/pretrained/model_base.pth'

max_words: 32

# vit video encoder
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

batch_size_train: 16
batch_size_test: 16
init_lr: 1e-5

num_frames: 1
num_frm_train: 1
num_frm_test: 1

image_size: 384
queue_size: 57600
alpha: 0.4
k_test: 128
negative_all_rank: False

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 6

#ToMe 
token_merging: True
trace_source: False
tome_r: [37, 16, 16, 16, 16, 16, 16, 8, 8, 8, 8, 8]
tome_prop_attn: True
tome_type: 'soft_s_multi_cls'
tome_min_token: 1
tome_hierarchy: True
tome_token_importance: False
tome_importance_alpha: 6.0
frame_flatten_type: "keep"
tome_average_type: "AVG"
frame_flatten_layer: []
frame_mask: False
attn_frame_mask_layer: []
merge_frame_mask_layer: []
binary_frame_mask: False
flatten_layer_merge_type: []
enable_frame_pos_embed: False
