video_root: '/data5/wancong/zhiyin/msrvtt/MSRVTT_Videos_Compression'
train_split_root: '/data5/wancong/zhiyin/msrvtt/MSRVTT_train.9k.csv'
test_split_root: '/data5/wancong/zhiyin/msrvtt/MSRVTT_JSFUSION_test.csv'
data_root: '/data5/wancong/zhiyin/msrvtt/MSRVTT_data.json'
dataset: 'retrieval_msrvtt'

# set pretrained as a file path or an url
pretrained: '/data5/wancong/zhiyin/TESTA-main/pretrained/testa_model_base_pretrain.pth'

# token merging
token_merging: False
testa_r: [1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,]
merging_type: frame&patch

max_words: 30

# timesformer video encoder
vit: 'timesformer'
patch_size: 16
learnable_temporal_scaling: False
attention_type: 'space_only'
vit_grad_ckpt: False
vit_ckpt_layer: 0
vision_width: 768  # 1024
num_heads: 12  # 16

# vit video encoder
# vit: 'base'
# vit_grad_ckpt: False
# vit_ckpt_layer: 0

batch_size_train: 8
batch_size_test: 32
init_lr: 1e-5

num_frames: 12
num_frm_train: 12
num_frm_test: 12

image_size: 224
queue_size: 32
alpha: 0.4
k_test: 128
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10

